import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { FEATURED_EPISODES, listenForArea, regulatoryEditorialArticle, relatedCoverageLinks, sameEditorialArticle, visibleForArea } from "../app/briefing-preview/edition.ts";

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const preview = read("app/briefing-preview/EditorialReadout.tsx");
const edition = read("app/briefing-preview/edition.ts");
const previewCss = read("app/briefing-preview/preview.css");
const briefingRoute = read("app/api/briefing/route.ts");
const readoutRequest = read("app/briefing-preview/readoutRequest.ts");
const readoutServer = read("lib/readoutWindowServer.ts");
const readoutCacheRoute = read("app/api/readout-cache/route.ts");
const middleware = read("middleware.ts");
const readoutNextPage = read("app/readout-next/page.tsx");
const vercelConfig = read("vercel.json");

test("the compact briefing keeps the physician evidence layer intact", () => {
  assert.match(preview, /PhysicianVoices/);
  assert.match(preview, /Shared, no commentary yet\./);
  assert.match(preview, /is-single/);
  assert.match(preview, /isTitleOnlyShare/);
  assert.match(preview, /posts\.slice\(0, 2\)/);
  assert.match(preview, /\$\{extraComments\} more comment/);
  assert.match(preview, /\{post\.text\}/);
  assert.match(preview, /post\.tweetUrl/);
  assert.match(preview, /article\?\.faces/);
  assert.match(preview, /function xAvatars/);
  assert.doesNotMatch(preview, /Promise\.allSettled/);
  assert.match(preview, /const sharedBy = article\?\.kolSharers \?\? item\.sharedBy/);
  assert.match(preview, /function shareCommentaryLabel/);
  assert.match(preview, /Shared by \$\{sharedBy\} clinician/);
  assert.match(preview, /1 commentary/);
  assert.match(preview, /visible < authoredCount/);
  assert.match(preview, /clinician comments/);
  assert.match(preview, /function clinicianSharers/);
  assert.match(preview, /post\.repostedBy/);
  assert.match(preview, /engagementScore/);
  assert.match(preview, /right\.score - left\.score/);
  assert.match(preview, /SHARER_PREVIEW_LIMIT = 3/);
  assert.match(preview, /SHARER_EXPANDED_LIMIT = 12/);
  assert.match(preview, /function PeerRow/);
  assert.match(preview, /<PeerRow article=\{article\} sharedBy=\{sharedBy\} \/>/);
  assert.match(preview, /article\.sharerPeople/);
  assert.match(preview, /clinicianSharers\(article\)\.slice\(0, sharedBy\)/);
  assert.match(preview, /other clinician/);
  assert.match(preview, /function CompactClinicianComment/);
  assert.match(preview, /applyEvidenceOverlay/);
  assert.match(preview, /function articleWithLiveEvidence/);
  assert.match(preview, /const base = overlay \? findArticle\(item, briefs\) \?\? articleFromEditorial\(item\) : articleFromEditorial\(item\)/);
  assert.doesNotMatch(preview, /applyEvidenceOverlay\(findArticle\(item, briefs\)/);
  assert.match(preview, /windowPayload\?\.overlays/);
  assert.doesNotMatch(preview, /EVIDENCE_REFRESH_MS|mode: "evidence-overlay"/);
  assert.doesNotMatch(preview, /window\.setInterval|window\.addEventListener\("focus"/);
  assert.match(edition, /articleEvidencePool/);
  assert.match(edition, /brief\.topStories/);
  assert.match(edition, /brief\.movers/);
  assert.match(edition, /brief\.trials/);
  assert.doesNotMatch(preview, /er-conversation-toggle/);
  assert.doesNotMatch(preview, /summari[sz]e.*post|synthetic.*quote/i);
});
